### ISSUE TITLE
Push release to fix readme on gatsby plugin library

### ISSUE THREAD

**Issue by lannonbr** [Mike-Dax/gatsby-remark-videos#5]
Currently the plugin's readme is based on the one on NPM which still has the bug that there was some missing commas. Could there be a patch release so the readme showing up on the gatsby plugin library doesn't have the broken example.

**Comment by jhodges10** [comment]
Seconded... I spent 15 minutes trying to figure out why my code wasn't compiling before realizing the example had a missing comma.

**Comment by Mike-Dax** [comment]
This is pushed now.
